# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MidPoint' do
pod 'Firebase', '>= 2.3.2'
end

target 'MidPointTests' do
pod 'Firebase', '>= 2.3.2'
end

